title: Адвокат Светломир Иванов гр.Русе
destination: docs
description: "Адвокат Светломир Иванов предлага правни консултации, изготвяне на становища, представителство пред съд и други държавни институции"
# baseurl: "https://advokativanov.eu"
url: "https://advokativanov.eu"
# url: ""
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs,LICENCE.txt, LICENCE-images.txt]
# Build settings
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag