title: Адвокат Светломир Иванов
email: g_cirkova@mail.bg
description: Website of lawyer Svetlomir Ivanov!
destination: docs
# baseurl: "/lawyer-s-website"
# baseurl: ""
url: "http://advokativanov.eu"
twitter_username: GerganaTsirkova
github_username: GerganaTsirkova
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs]
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
